# Site settings
title: Your awesome title
email: your-email@domain.com
author: Your name
language: zh-cn
defaultFileType: audio/mpeg
explicit: no
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/podcast-example"
url: "http://ze3kr.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
