# 网页设置 (请务必仔细修改)
title: 制作播客 (Podcast) - 帮助与实践 (事例)
email: your-email@example.com
author: Your name
language: zh-cn
defaultFileType: audio/mpeg
explicit: no
description: "从文件服务器、RSS Feed生成与存放、域名解析到Hello World、网页制作、发布到iTunes。开源的项目，向您介绍如何制作Podcast。"
baseurl: "/podcast-example"
url: "http://git.ze3kr.com"
twitter_username: ze3kr
github_username:  ZE3kr/podcast-example

# 屏蔽设置 (在提交iTunes时，请将此值修改为no。如果值为Yes，则播客不会出现在iTunes)
blockitunes: yes

# 建站设置
markdown: kramdown
permalink: pretty
